services:
  mongodb:
    image: mongo:latest
    container_name: notification-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: notification-rabbitmq
    restart: always
    ports:
      - "5672:5672"     # Port dla aplikacji
      - "15672:15672"   # Port dla panelu zarządzania (GUI)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  mongo_data:
